defaults: &defaults
  docker:
    - image: circleci/node:6
      environment:
        JOBS: 2
  working_directory: ~/ember-cli-deploy-aws-pack

version: 2
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install --non-interactive --no-lockfile

workflows:
  version: 2
  test_install:
    jobs:
      - install_dependencies
